sudo: required
services:
- docker
env:
- EXPLORER_VER=v4.7.47
before_script:
- wget -q https://$SOURCE_URL/source/marand/files/ehrexplorer-$EXPLORER_VER.zip -O
  ehrexplorer.zip && unzip -j ehrexplorer.zip explorer4.war -d source && rm ehrexplorer.zip
  && mv source/explorer4.war source/explorer.war
script:
- envsubst < Dockerfile > Dockerfile.$EXPLORER_VER
- docker build -f Dockerfile.$EXPLORER_VER --tag marand-thinkehr-explorer .
after_script:
- docker images
before_deploy:
- docker login $REGISTRY_URL -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag marand-thinkehr-explorer "${REGISTRY_URL}"/marand-thinkehr-explorer:${EXPLORER_VER}
deploy:
  provider: script
  script: docker push "${REGISTRY_URL}"/marand-thinkehr-explorer:${EXPLORER_VER}
  on:
    branch: master
notifications:
  slack:
    secure: FI+vENP17DcXDm/x72wfKsxdh5n+yP0CPUjDAgpTUYgdlsxM0EnAacJGghlE2yw5G6NSJ99E6oAlydFPGdKaY4XZKpSO+irTYhSgTeRf+njGdQz/9wTA+FMBGLBZjpiX4uCg0dR1HlyR2FcDd1MQ259+nMfFobVjzArJZxhuIrEeK5lUdZ1CxguM51OnWYCTKD3rh3Tf/PWfyGWTDPrjODkDEqmatAc4fgCls3B6nAA7hyiiFEwSiDn02E6D36VYPKhN9nO4E8BUnBC9dcu/DXu56a6kHMRFLmSM9Atvy1dtX+mVzhn1CNAirokhqbQQ9uH5ffVOglLl0CuqgbqL+sUGKNDMOrEgvsP0mSD6AsCCLCYZCXOATPRwPcovPpebLiQl5D4EZoB4XxonRfKdALVpXYcprnMeCZYAwut+yObXE6S+dAJhxrJMqJTJZqoca+H7f+m5jBNGM/SIaYC/RZy8kK/WFfXxz5e6K5TJYJjfX9whRsb1GK9mZ5/kkG48ycW/lRqlGzePo475ikSdKdaHOE2C5pVMfov8r/sALzeTqXmmVNjPmhkhp1AqNJx7y1kbev5qXX7QyrLHZXDiBsQQ+kRpW0nNPjrZcBXWlMK9hK9LcpJswPxDVv0C4dReob8UL3SNsWGxBsN1sTNj9nUxikhsKA+WVYROhUUq9E8=
