sudo: required
services:
- docker
env:
- EXPLORER_VER=v4.7.47
before_script:
- wget -q https://$SOURCE_URL/source/marand/files/ehrexplorer-$EXPLORER_VER.zip &&
  unzip ehrexplorer-$EXPLORER_VER.zip -d source && rm ehrexplorer-$EXPLORER_VER.zip
script:
- envsubst < Dockerfile > Dockerfile.$EXPLORER_VER
- docker build -f Dockerfile.$EXPLORER_VER --tag marand-thinkehr-explorer .
after_script:
- docker images
before_deploy:
- docker login $REGISTRY_URL -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag marand-thinkehr-explorer "${REGISTRY_URL}"/marand-thinkehr-explorer:${EXPLORER_VER}
deploy:
  provider: script
  script: docker push "${REGISTRY_URL}"/marand-thinkehr-explorer:${THINKEHR_VER}
  on:
    branch: master
notifications:
  slack:
    secure: BHeje1HqLEijRPZWzjiJEWPFJsS+xHpDoZVFJcGGPhkhxHR21sSGS3qiPhKQ8IlBy+84Aytf02QALwH5yo98sYZ9K1hYc1DmNNmDai5FIAyYIIH4bziuV95s5bg2kJLe7ftmSY0SreDpej1DwtU1P48vJ07y3otfIUUOxlahn0rQf//7O4DLcDBSay4dkvcUAXwLiiQDLcjWampQfzrQWjI3eO0AO0IPR6132Fpg1fmRBQhdkyQg5rrCVE91cZT+NM8mrDrKenOa0D13jfbvmqenMXFrt3MHaVpmKU/JXqb2VOWNqa7Sr2aZM5ymquYb9m2q9wHFMi8Syk3Nv6O7IgAoF+VDrsLSZAnyoSiN9egYpHCPTQbNno0PWyJF/T84MMNgc9fuMUEmDL/LsvHnqGi/f7biZn6TnUWYPgfo2k0sbFqaTOCLCEVqkkUA0Ez4YDuhQbdRznCts0vN84KE1Mssc22OxNhLf85t58fQmCTYCqLGHpbrGeRUtteWC8ogzcteH7aQZ3KWcIkWaDJUpxzbYppZ6YXtQgG6YfxSDhWXc7107JOdKqA/jjEVq7GWkRbu1+xNjhbmHs3Ctm4dDju8AMVd9whJOZQFPY/tcF3EUD9lIqZDnIKEtgJL/ljSWr0Th9tyitjlvOUIkxAVNmya4QZMzyWbNh+myisLUgI=
